# Generated by Django 5.0.3 on 2024-04-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('profile_picture', models.ImageField(upload_to='candidate_profile_pics')),
            ],
        ),
    ]
