# Generated by Django 5.0.3 on 2024-04-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='department',
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(default='Product', max_length=100),
            preserve_default=False,
        ),
    ]
